### ISSUE TITLE
Smatch v2.0 crashes on a graph

### ISSUE THREAD

**Issue by mdtux89** [amrisi/amr-guidelines#164]
Hi, for the following graph:
```
(c2 / contrast
      :op2 (p / person
            :domain (i / i)
            :polarity -
            :ARG0-of (e / explore-01)))
```
Smatch-2.0 gives the error:

```
Traceback (most recent call last):
  File "smatch.py", line 833, in <module>
    main(args)
  File "smatch.py", line 734, in main
    amr1.rename_node(prefix1)
  File "/afs/inf.ed.ac.uk/user/s13/s1333293/smatch_2.0/amr.py", line 86, in rename_node
    new_dict[node_map_dict[k]] = v
KeyError: '-'
```

This does not happen for the online demo or the v1.0.

Marco

**Comment by nschneid** [comment]
Response from today's AMR call: the shared task has released an update, v. 2.0.2, that fixes some bugs: http://alt.qcri.org/semeval2016/task8/index.php?id=data-and-tools

A more dramatic rewrite of the innards of smatch will be released soon as v. 2.2.

**Comment by mdtux89** [comment]
v2.0.2 solves the problem.
